version: "3.3"

services:

  otus-scoring-api:
    build: .
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4500:8080"
    links:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
